<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->truncate();

        DB::table('products')->insert([
            // Kategori 1: Sepatu Safety Boot
            [
                'nama' => 'Sepatu Safety Cheetah 7111',
                'harga' => 350000,
                'rating' => 4.8,
                'kategori_id' => 1,
                'material' => 'Kulit Sintetis',
                'stok' => 50,
                'seller' => 'Toko Mitra Jaya',
                'promo' => 'Diskon 10%',
                'best' => true,
                'image' => 'products/sepatu_safety.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sepatu Safety King KWD 805',
                'harga' => 420000,
                'rating' => 4.9,
                'kategori_id' => 1,
                'material' => 'Kulit Asli',
                'stok' => 30,
                'seller' => 'Gudang Atap Mandiri',
                'promo' => null,
                'best' => false,
                'image' => 'products/sepatu_safety.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sepatu Krisbow Arrow',
                'harga' => 280000,
                'rating' => 4.5,
                'kategori_id' => 1,
                'material' => 'Karet & Canvas',
                'stok' => 100,
                'seller' => 'Toko Sumber Material',
                'promo' => 'Gratis Ongkir',
                'best' => false,
                'image' => 'products/sepatu_safety.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Kategori 2: Pipa PVC
            [
                'nama' => 'Pipa PVC Wavin 4 Inch (AW)',
                'harga' => 95000,
                'rating' => 4.7,
                'kategori_id' => 2,
                'material' => 'PVC',
                'stok' => 200,
                'seller' => 'Toko Mitra Jaya',
                'promo' => 'Best Seller',
                'best' => true,
                'image' => 'products/pipa_pvc.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pipa PVC Rucika 2 Inch (D)',
                'harga' => 45000,
                'rating' => 4.8,
                'kategori_id' => 2,
                'material' => 'PVC',
                'stok' => 150,
                'seller' => 'CV Tangsel Konstruksi',
                'promo' => null,
                'best' => false,
                'image' => 'products/pipa_pvc.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sambungan Pipa PVC (Elbow)',
                'harga' => 15000,
                'rating' => 4.6,
                'kategori_id' => 2,
                'material' => 'PVC',
                'stok' => 500,
                'seller' => 'Gudang Atap Mandiri',
                'promo' => 'Promo Diskon',
                'best' => false,
                'image' => 'products/pipa_pvc.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kategori 3: Atap
            [
                'nama' => 'Atap Spandek Galvalum 0.3mm',
                'harga' => 48000,
                'rating' => 4.8,
                'kategori_id' => 3,
                'material' => 'Galvalum',
                'stok' => 300,
                'seller' => 'CV Tangsel Konstruksi',
                'promo' => 'Harga Spesial',
                'best' => true,
                'image' => 'products/atap_galvalum.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Genteng Metal Pasir',
                'harga' => 35000,
                'rating' => 4.7,
                'kategori_id' => 3,
                'material' => 'Metal Pasir',
                'stok' => 400,
                'seller' => 'Toko Sumber Material',
                'promo' => null,
                'best' => false,
                'image' => 'products/atap_galvalum.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Atap Bitumen Onduline',
                'harga' => 155000,
                'rating' => 4.9,
                'kategori_id' => 3,
                'material' => 'Bitumen',
                'stok' => 120,
                'seller' => 'Gudang Atap Mandiri',
                'promo' => 'Gratis Ongkir',
                'best' => false,
                'image' => 'products/atap_galvalum.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Kategori 4: Karpet Talang
            [
                'nama' => 'Karpet Talang PVC 90cm (Roll)',
                'harga' => 450000,
                'rating' => 4.6,
                'kategori_id' => 4,
                'material' => 'PVC',
                'stok' => 50,
                'seller' => 'Toko Mitra Jaya',
                'promo' => null,
                'best' => true,
                'image' => 'products/karpet_talang.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Karpet Talang Merah 60cm (Meteran)',
                'harga' => 15000,
                'rating' => 4.5,
                'kategori_id' => 4,
                'material' => 'Plastik HD',
                'stok' => 200,
                'seller' => 'Toko Sumber Material',
                'promo' => 'Ekonomis',
                'best' => false,
                'image' => 'products/karpet_talang.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kategori 5: Selang
            [
                'nama' => 'Selang Air Benang 5/8 Inch (Meteran)',
                'harga' => 7000,
                'rating' => 4.8,
                'kategori_id' => 5,
                'material' => 'PVC Benang',
                'stok' => 1000,
                'seller' => 'CV Tangsel Konstruksi',
                'promo' => 'Tahan Lama',
                'best' => true,
                'image' => 'products/selang_air.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Selang Taman Elastis Magic Hose 15m',
                'harga' => 65000,
                'rating' => 4.4,
                'kategori_id' => 5,
                'material' => 'Karet Elastis',
                'stok' => 200,
                'seller' => 'Toko Mitra Jaya',
                'promo' => 'Diskon 20%',
                'best' => false,
                'image' => 'products/selang_air.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Selang Hisap Spiral 2 Inch (Roll)',
                'harga' => 850000,
                'rating' => 4.9,
                'kategori_id' => 5,
                'material' => 'PVC Spiral',
                'stok' => 25,
                'seller' => 'Gudang Atap Mandiri',
                'promo' => null,
                'best' => false,
                'image' => 'products/selang_air.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}